### ISSUE TITLE
Roadmap to 0.2

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/centurion#1]
- [x] Build a js vendor package
- [ ] Remove rework.properties
- [ ] Watch files with the mocha method
- [ ] Livereload
- [x] Link to custom html boilerplate
- [ ] Be able to require as package
- [ ] Be able to add config as package
